
development:
  adapter: postgresql
  encoding: unicode
  database: connect_dev
  pool: 5
  username: con
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: connect_test
  pool: 5
  username: con
  password: root

production:
  adapter: postgresql
  encoding: unicode
  database: connect_prod
  pool: 5
  username: con
  password: root
