
development:
  adapter: postgresql
  encoding: unicode
  database: connect_to_frend_development
  pool: 5
  username: connect_to_frend
  password: root


  adapter: postgresql
  encoding: unicode
  database: connect_to_frend_test
  pool: 5
  username: connect_to_frend
  password: root

production:
  adapter: postgresql
  encoding: unicode
  database: connect_to_frend_production
  pool: 5
  username: connect_to_frend
  password: root
